<?php

/**
 * ProcessWire Replace Curly Quotes
 *
 * Automatically replace curly quotes with regular quotes
 * 
 * ProcessWire 2.x, 3.x
 * PHP >5.4
 * written by Eric "Twitch" Rodrigue 
 * Licensed under MIT, see LICENSE.TXT
 *https://github.com/twitchsbrew/TextformatterReplaceCurlyQuotes
 * 
 *
 */

class TextformatterReplaceCurlyQuotes extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'Replace Curly Quotes/Apostrophes', 
			'version' => 100,
			'href' => 'https://processwire.com/talk/topic/16907-textformatterreplacecurlyquotes/',
			'summary' => "Replaces single and double curly quotes/apostrophes with regular quotes/apostrophes", 
		); 
	}

	/**
     * Format the given text string.
     *
     * @param Page $page
     * @param Field $field
     * @param string $value
     */
    public function formatValue(Page $page, Field $field, &$value)
    {
      $chr_map = array(
   // Windows codepage 1252
   "\xC2\x82" => "'", // U+0082⇒U+201A single low-9 quotation mark
   "\xC2\x84" => '"', // U+0084⇒U+201E double low-9 quotation mark
   "\xC2\x8B" => "'", // U+008B⇒U+2039 single left-pointing angle quotation mark
   "\xC2\x91" => "'", // U+0091⇒U+2018 left single quotation mark
   "\xC2\x92" => "'", // U+0092⇒U+2019 right single quotation mark
   "\xC2\x93" => '"', // U+0093⇒U+201C left double quotation mark
   "\xC2\x94" => '"', // U+0094⇒U+201D right double quotation mark
   "\xC2\x9B" => "'", // U+009B⇒U+203A single right-pointing angle quotation mark

   // Regular Unicode     // U+0022 quotation mark (")
                          // U+0027 apostrophe     (')
   "\xC2\xAB"     => '"', // U+00AB left-pointing double angle quotation mark
   "\xC2\xBB"     => '"', // U+00BB right-pointing double angle quotation mark
   "\xE2\x80\x98" => "'", // U+2018 left single quotation mark
   "\xE2\x80\x99" => "'", // U+2019 right single quotation mark
   "\xE2\x80\x9A" => "'", // U+201A single low-9 quotation mark
   "\xE2\x80\x9B" => "'", // U+201B single high-reversed-9 quotation mark
   "\xE2\x80\x9C" => '"', // U+201C left double quotation mark
   "\xE2\x80\x9D" => '"', // U+201D right double quotation mark
   "\xE2\x80\x9E" => '"', // U+201E double low-9 quotation mark
   "\xE2\x80\x9F" => '"', // U+201F double high-reversed-9 quotation mark
   "\xE2\x80\xB9" => "'", // U+2039 single left-pointing angle quotation mark
   "\xE2\x80\xBA" => "'", // U+203A single right-pointing angle quotation mark
);
$chr = array_keys  ($chr_map); // but: for efficiency you should
$rpl = array_values($chr_map); // pre-calculate these two arrays
$value = str_replace($chr, $rpl, html_entity_decode($value, ENT_QUOTES, "UTF-8"));
}

}

	
